development:
  adapter: postgresql
  encoding: unicode
  database: store_production
  pool: 5
  host: localhost
  username: ramirin
  password: 214365

test:
  adapter: postgresql
  encoding: unicode
  database: store_production
  pool: 5
  host: localhost
  username: ramirin
  password: 214365

production:
  adapter: postgresql
  encoding: unicode
  database: store_production
  pool: 5
  host: localhost
  username: ramirin
  password: 214365